**Introduction to Python for data analysis**\
March 18, 2025\
Basics of numpy

In this notebook, we going to learn briefly about numpy.

**Import numpy**

In [1]:
import numpy as np

**Create an array**

In [2]:
arr = np.arange(6).reshape(3, 2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

There are different ways to create an array

In [10]:
# Create several arrays
arr2 = np.array([2, 3, 4])

arr3 = np.array([(2,3,4), (5,6,7)])

arr4 = np.zeros((2,3))

arr5 = np.ones((2,3))

# Print
print('This is arr2:\n', arr2, '\n')
print('This is arr3:\n', arr3, '\n')
print('This is arr4:\n', arr4, '\n')
print('This is arr5:\n', arr5, '\n')

This is arr2:
 [2 3 4] 

This is arr3:
 [[2 3 4]
 [5 6 7]] 

This is arr4:
 [[0. 0. 0.]
 [0. 0. 0.]] 

This is arr5:
 [[1. 1. 1.]
 [1. 1. 1.]] 



**Types of an array**

In [11]:
# 1d array
arr1d = np.arange(18)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [12]:
# 2d array
arr2d = arr1d.reshape(6,3)
arr2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [13]:
# 3d array
arr3d = arr1d.reshape(3,3,2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

**Attributes of a numpy array**

In [17]:
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
arr.ndim

2

In [15]:
arr.shape

(3, 2)

In [16]:
arr.dtype

dtype('int64')

**Math operations**

In [18]:
# Sum
np.sum(arr)

15

In [19]:
# Mean
np.mean(arr)

2.5

In [20]:
# Min max - this find the values
print(np.min(arr))
print(np.max(arr))

0
5


In [21]:
# Argmin argmax - this find the index
print(np.argmin(arr))
print(np.argmax(arr))

0
5


**Indexing and slicing**

In [22]:
# Create an array
arr = np.array([10, 20, 30, 50])
arr

array([10, 20, 30, 50])

Basic slicing

In [23]:
arr[0:2]

array([10, 20])

Boolean indexing